# Generated by Django 6.0 on 2025-12-23 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('bungalow', 'Bungalow/Independent'), ('building', 'Apartment Building')], max_length=20)),
                ('address', models.TextField()),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('flat_no', models.CharField(blank=True, max_length=50, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('subscription_active', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_phone', models.CharField(max_length=20)),
                ('visitor_photo', models.ImageField(upload_to='visitors/')),
                ('reason', models.CharField(choices=[('delivery', 'Delivery'), ('guest', 'Guest'), ('service', 'Service'), ('family', 'Family'), ('meeting', 'Meeting'), ('other', 'Other')], max_length=20)),
                ('other_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
    ]
